# Site settings
title: Ekaterina Aristova
email: k.aristova@gmail.com
description: "Ekaterina Aristova's portfolio and blog."
baseurl: ""
url: "http://www.aristova.me"

# Build settings
markdown: kramdown
permalink: pretty
